name: korean_lifeline
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# 2. 패키지 설정 (맨 왼쪽 벽에 붙여서 새로 작성)
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
#  image_path: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon_ios.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
#  adaptive_icon_foreground: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon_ios.png"
# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true
  assets:
    - assets/images/

